### ISSUE TITLE
Add Usernames 

### ISSUE THREAD

**Issue by flutterflies** [flutterflies/corkboard#5]
Allows Users to have usernames

**Comment by Seunadex** [comment]
@flutterflies I'll like to work on this, i understand what it is expected but if you have more info, kindly let me know. and when user logs in should the username be displayed instead of the email?

**Comment by flutterflies** [comment]
You should be able to log in with either a username or an email. Usernames should be displayed in place of emails in the navbar in the area shown below and usernames should be a required field

**Comment by Seunadex** [comment]
@flutterflies I have a PR up, kindly review/test and give me feedback

**Comment by flutterflies** [comment]
closed by #11
